// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmniMonitor.Server.Context;

#nullable disable

namespace OmniMonitor.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250926235641_MigrationDataset")]
    partial class MigrationDataset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Id_Group")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Source")
                        .HasColumnType("int");

                    b.Property<string>("Is_Dataset")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SensorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_device")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetDevices");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Permite ver la lista de usuarios",
                            Name = "Ver Usuarios"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Permite crear nuevos usuarios",
                            Name = "Crear Usuarios"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Permite editar usuarios existentes",
                            Name = "Editar Usuarios"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Permite eliminar usuarios",
                            Name = "Eliminar Usuarios"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Permite ver datos de sensores",
                            Name = "Ver Sensores"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Permite configurar sensores",
                            Name = "Configurar Sensores"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Permite ver la lista de empleados",
                            Name = "Ver Empleados"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Permite crear, editar y eliminar empleados",
                            Name = "Gestionar Empleados"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Permite ver la lista de items",
                            Name = "Ver Items"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Permite crear, editar y eliminar items",
                            Name = "Gestionar Items"
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rol con acceso completo al sistema",
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Rol con acceso limitado de solo lectura",
                            Name = "Visitante"
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 9,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenIM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenExpirationAM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpirationEM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpirationIM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpirationUM")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "visitante",
                            Username = "visitante"
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetDevice", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.Dataset", "Dataset")
                        .WithMany("DatasetDevices")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.RolePermission", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniMonitor.Shared.Dtos.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.UserRole", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniMonitor.Shared.Dtos.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Dataset", b =>
                {
                    b.Navigation("DatasetDevices");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
