// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmniMonitor.Server.Context;

#nullable disable

namespace OmniMonitor.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251012173411_reportsMigraton")]
    partial class reportsMigraton
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrossModuleJoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("JoinType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeftOperandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RightOperandId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LeftOperandId");

                    b.HasIndex("RightOperandId");

                    b.ToTable("CrossModuleJoins");
                });

            modelBuilder.Entity("JoinOperand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("JoinPropertyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModuleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JoinOperands");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_alert")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetAlerts");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_device")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetDevices");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtensionState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_Alert")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Event")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Extension")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Resource")
                        .HasColumnType("int");

                    b.Property<string>("Is_Dataset")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResourceState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("DatasetsEM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_event")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetEvents");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEventEM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_event")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetEventsEM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetExtension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_extension")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetExtensions");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetIM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Id_Group")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Source")
                        .HasColumnType("int");

                    b.Property<string>("Is_Dataset")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SensorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("DatasetsIM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetNews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_news")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetNews");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_resource")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetResources");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetUM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_News")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Zone")
                        .HasColumnType("int");

                    b.Property<string>("Is_Dataset")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("DatasetsUM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.GrupoDataset", b =>
                {
                    b.Property<int>("IdGroupDataset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGroupDataset"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int")
                        .HasColumnName("id_dataset");

                    b.Property<string>("JsonDesign")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("JSON_design");

                    b.Property<int>("VisualizacionId")
                        .HasColumnType("int")
                        .HasColumnName("Id_visualizacion");

                    b.HasKey("IdGroupDataset");

                    b.HasIndex("DatasetId");

                    b.HasIndex("VisualizacionId");

                    b.ToTable("GrupoDatasets");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Permite ver la lista de usuarios",
                            Name = "Ver Usuarios"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Permite crear nuevos usuarios",
                            Name = "Crear Usuarios"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Permite editar usuarios existentes",
                            Name = "Editar Usuarios"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Permite eliminar usuarios",
                            Name = "Eliminar Usuarios"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Permite ver datos de sensores",
                            Name = "Ver Sensores"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Permite configurar sensores",
                            Name = "Configurar Sensores"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Permite ver la lista de empleados",
                            Name = "Ver Empleados"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Permite crear, editar y eliminar empleados",
                            Name = "Gestionar Empleados"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Permite ver la lista de items",
                            Name = "Ver Items"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Permite crear, editar y eliminar items",
                            Name = "Gestionar Items"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Permite ver datasets del módulo UM (Zonas, Eventos, Noticias)",
                            Name = "Ver Datasets UM"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Permite crear nuevos datasets del módulo UM",
                            Name = "Crear Datasets UM"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Permite eliminar datasets del módulo UM",
                            Name = "Eliminar Datasets UM"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Permite ver datasets del módulo EM (Alertas, Eventos, Extensiones, Recursos)",
                            Name = "Ver Datasets EM"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Permite crear nuevos datasets del módulo EM",
                            Name = "Crear Datasets EM"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Permite eliminar datasets del módulo EM",
                            Name = "Eliminar Datasets EM"
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rol con acceso completo al sistema",
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Rol con acceso limitado de solo lectura",
                            Name = "Visitante"
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 25,
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 26,
                            PermissionId = 14,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenIM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenExpirationAM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpirationEM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpirationIM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpirationOM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpirationUM")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "visitante",
                            Username = "visitante"
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Visualizacion", b =>
                {
                    b.Property<int>("IdVisualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVisualizacion"));

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_from");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_to");

                    b.Property<string>("JsonDesign")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("JSON_design");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdVisualizacion");

                    b.ToTable("Visualizaciones");
                });

            modelBuilder.Entity("Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ReportJoin", b =>
                {
                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("CrossModuleJoinId")
                        .HasColumnType("int");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("int");

                    b.HasKey("ReportId", "CrossModuleJoinId");

                    b.HasIndex("CrossModuleJoinId");

                    b.ToTable("ReportJoins");
                });

            modelBuilder.Entity("CrossModuleJoin", b =>
                {
                    b.HasOne("JoinOperand", "LeftOperand")
                        .WithMany()
                        .HasForeignKey("LeftOperandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JoinOperand", "RightOperand")
                        .WithMany()
                        .HasForeignKey("RightOperandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeftOperand");

                    b.Navigation("RightOperand");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetAlert", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetEM", "Dataset")
                        .WithMany("DatasetAlerts")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetDevice", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetIM", "Dataset")
                        .WithMany("DatasetDevices")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEvent", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetUM", "Dataset")
                        .WithMany("DatasetEvents")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEventEM", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetEM", "Dataset")
                        .WithMany("DatasetEvents")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetExtension", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetEM", "Dataset")
                        .WithMany("DatasetExtensions")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetNews", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetUM", "Dataset")
                        .WithMany("DatasetNews")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetResource", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetEM", "Dataset")
                        .WithMany("DatasetResources")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.GrupoDataset", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetIM", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniMonitor.Shared.Dtos.Visualizacion", "Visualizacion")
                        .WithMany("GrupoDatasets")
                        .HasForeignKey("VisualizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("Visualizacion");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.RolePermission", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniMonitor.Shared.Dtos.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.UserRole", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniMonitor.Shared.Dtos.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReportJoin", b =>
                {
                    b.HasOne("CrossModuleJoin", "CrossModuleJoin")
                        .WithMany()
                        .HasForeignKey("CrossModuleJoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Report", "Report")
                        .WithMany("ReportJoins")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrossModuleJoin");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEM", b =>
                {
                    b.Navigation("DatasetAlerts");

                    b.Navigation("DatasetEvents");

                    b.Navigation("DatasetExtensions");

                    b.Navigation("DatasetResources");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetIM", b =>
                {
                    b.Navigation("DatasetDevices");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetUM", b =>
                {
                    b.Navigation("DatasetEvents");

                    b.Navigation("DatasetNews");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Visualizacion", b =>
                {
                    b.Navigation("GrupoDatasets");
                });

            modelBuilder.Entity("Report", b =>
                {
                    b.Navigation("ReportJoins");
                });
#pragma warning restore 612, 618
        }
    }
}
