// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmniMonitor.Server.Context;

#nullable disable

namespace OmniMonitor.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250915132407_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.SensorClimax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Co2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Humedad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HumedadDelSuelo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelDeRuido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivleDeBrillo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Potencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temperatura")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemperaturaDelSuelo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SensorClimaxs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Co2 = 400,
                            Humedad = 55,
                            HumedadDelSuelo = 20,
                            NivelDeRuido = 50,
                            NivleDeBrillo = 300,
                            Potencia = 150,
                            Temperatura = 24,
                            TemperaturaDelSuelo = 18
                        },
                        new
                        {
                            Id = 2,
                            Co2 = 420,
                            Humedad = 60,
                            HumedadDelSuelo = 22,
                            NivelDeRuido = 55,
                            NivleDeBrillo = 320,
                            Potencia = 160,
                            Temperatura = 25,
                            TemperaturaDelSuelo = 19
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SondaToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenExpiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin123",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "password123",
                            Username = "usuario1"
                        },
                        new
                        {
                            Id = 3,
                            Password = "test123",
                            Username = "test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
