// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmniMonitor.Server.Context;

#nullable disable

namespace OmniMonitor.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
<<<<<<<< HEAD:OmniMonitor/Server/Migrations/20251110045420_InitialMigration.Designer.cs
    [Migration("20251110045420_InitialMigration")]
    partial class InitialMigration
========
    [Migration("20251113031423_AddLinkToVisualizationl")]
    partial class AddLinkToVisualizationl
>>>>>>>> 3273e80 (ahora bastante segura):OmniMonitor/Server/Migrations/20251113031423_AddLinkToVisualizationl.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrossModuleJoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("JoinType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeftOperandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RightOperandId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LeftOperandId");

                    b.HasIndex("RightOperandId");

                    b.ToTable("CrossModuleJoins");
                });

            modelBuilder.Entity("DatasetReports", b =>
                {
                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("DatasetsOfReportsId")
                        .HasColumnType("int");

                    b.HasKey("ReportId", "DatasetsOfReportsId");

                    b.HasIndex("DatasetsOfReportsId");

                    b.ToTable("DatasetReports");
                });

            modelBuilder.Entity("DatasetsOfReports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ModuleType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("id_dataset")
                        .HasMaxLength(256)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DatasetsOfReports");
                });

            modelBuilder.Entity("JoinOperand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("JoinPropertyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModuleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JoinOperands");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OmniMonitor.Server.Models.SharedLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DashboardId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("SharedLinks");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DashboardDto", b =>
                {
                    b.Property<int>("IdDashboard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_dashboard");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDashboard"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int?>("GrupoVisualizacion")
                        .HasColumnType("int")
                        .HasColumnName("grupo_visualizacion");

                    b.Property<string>("JsonDiseno")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("JSON_diseño");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("username");

                    b.HasKey("IdDashboard");

                    b.HasIndex("Username");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetAM", b =>
                {
                    b.Property<int>("Id_Dataset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Dataset"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Filters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_Asset_Type")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Event_Task")
                        .HasColumnType("int");

                    b.Property<string>("Is_Dataset")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type_Dataset")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id_Dataset");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetAM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_alert")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetAlerts");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetAsset", b =>
                {
                    b.Property<int>("Grupo_Asset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Grupo_Asset"));

                    b.Property<int>("DatasetAMId")
                        .HasColumnType("int");

                    b.Property<string>("Id_Asset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Grupo_Asset");

                    b.HasIndex("DatasetAMId");

                    b.ToTable("DatasetAsset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_Category")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetCategory");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_device")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetDevices");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Filters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Is_Dataset")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetsEM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_event")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetEvents");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEventEM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_event")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetEventsEM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEventTaskInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetAMId")
                        .HasColumnType("int");

                    b.Property<int>("Id_Event_Task_Instance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetAMId");

                    b.ToTable("DatasetEventTaskInstance");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetExtension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_extension")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetExtensions");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetIM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Id_Group")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Source")
                        .HasColumnType("int");

                    b.Property<string>("Is_Dataset")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SensorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetsIM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetNews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int>("Id_news")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetNews");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetStock", b =>
                {
                    b.Property<int>("Grupo_Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Grupo_Stock"));

                    b.Property<int>("DatasetAMId")
                        .HasColumnType("int");

                    b.Property<int?>("DatasetEventTaskInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("Id_Stock")
                        .HasColumnType("int");

                    b.HasKey("Grupo_Stock");

                    b.HasIndex("DatasetAMId");

                    b.HasIndex("DatasetEventTaskInstanceId");

                    b.ToTable("DatasetStock");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetUM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Filters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_Zone")
                        .HasColumnType("int");

                    b.Property<string>("Is_Dataset")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetsUM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Datasets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameDataset")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TipoDataset")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.GrupoDataset", b =>
                {
                    b.Property<int>("IdGroupDataset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGroupDataset"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int")
                        .HasColumnName("id_dataset");

                    b.Property<string>("JsonDesign")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("JSON_design");

                    b.Property<int>("VisualizacionId")
                        .HasColumnType("int")
                        .HasColumnName("Id_visualizacion");

                    b.HasKey("IdGroupDataset");

                    b.HasIndex("DatasetId");

                    b.HasIndex("VisualizacionId");

                    b.ToTable("GrupoDatasets");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.GrupoVisualizacion", b =>
                {
                    b.Property<int>("IdGrupoVisualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_grupo_visualizacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupoVisualizacion"));

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_agregado");

                    b.Property<int>("GrupoVisualizacionId")
                        .HasColumnType("int")
                        .HasColumnName("grupo_visualizacion");

                    b.Property<int?>("IdVisualizacion")
                        .HasColumnType("int")
                        .HasColumnName("id_visualizacion");

                    b.Property<int?>("KpiId")
                        .HasColumnType("int")
                        .HasColumnName("id_kpi");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<string>("PropsConfiguracion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("props_configuracion");

                    b.Property<int>("TipoCard")
                        .HasColumnType("int")
                        .HasColumnName("tipo_card");

                    b.HasKey("IdGrupoVisualizacion");

                    b.HasIndex("GrupoVisualizacionId");

                    b.HasIndex("IdVisualizacion");

                    b.HasIndex("KpiId");

                    b.ToTable("GrupoVisualizaciones");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Kpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Atributo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "atributo");

                    b.Property<string>("ColorRanges")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "colorRanges");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "datasetId");

                    b.Property<string>("DefaultColor")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "defaultColor");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "extraInfo");

                    b.Property<string>("Metric")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "metric");

                    b.Property<double?>("Multiplier")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "multiplier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "sourceModule");

                    b.Property<int?>("Type")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "unit");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "username");

                    b.HasKey("Id");

                    b.ToTable("Kpi");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Permite ver la lista de usuarios",
                            Name = "Ver Usuarios"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Permite crear nuevos usuarios",
                            Name = "Crear Usuarios"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Permite editar usuarios existentes",
                            Name = "Editar Usuarios"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Permite eliminar usuarios",
                            Name = "Eliminar Usuarios"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Permite ver datos de sensores",
                            Name = "Ver Sensores"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Permite configurar sensores",
                            Name = "Configurar Sensores"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Permite ver la lista de empleados",
                            Name = "Ver Empleados"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Permite crear, editar y eliminar empleados",
                            Name = "Gestionar Empleados"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Permite ver la lista de items",
                            Name = "Ver Items"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Permite crear, editar y eliminar items",
                            Name = "Gestionar Items"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Permite ver datasets del módulo UM (Zonas, Eventos, Noticias)",
                            Name = "Ver Datasets UM"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Permite crear nuevos datasets del módulo UM",
                            Name = "Crear Datasets UM"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Permite eliminar datasets del módulo UM",
                            Name = "Eliminar Datasets UM"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Permite ver datasets del módulo EM (Alertas, Eventos, Extensiones, Recursos)",
                            Name = "Ver Datasets EM"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Permite crear nuevos datasets del módulo EM",
                            Name = "Crear Datasets EM"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Permite eliminar datasets del módulo EM",
                            Name = "Eliminar Datasets EM"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Permite ver dashboards personalizables",
                            Name = "Ver Dashboards"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Permite crear nuevos dashboards personalizables",
                            Name = "Crear Dashboards"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Permite editar dashboards existentes",
                            Name = "Editar Dashboards"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Permite eliminar dashboards",
                            Name = "Eliminar Dashboards"
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rol con acceso completo al sistema",
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Rol con acceso limitado de solo lectura",
                            Name = "Visitante"
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 27,
                            PermissionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 28,
                            PermissionId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 29,
                            PermissionId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 30,
                            PermissionId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 25,
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 26,
                            PermissionId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 31,
                            PermissionId = 17,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenIM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SondaTokenUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenExpirationAM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpirationEM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpirationIM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpirationOM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpirationUM")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Visualizacion", b =>
                {
                    b.Property<int>("IdVisualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVisualizacion"));

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_from");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_to");

                    b.Property<string>("JsonDesign")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("JSON_design");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdVisualizacion");

                    b.ToTable("Visualizaciones");
                });

            modelBuilder.Entity("Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("JSON_config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JSON_filters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ReportJoin", b =>
                {
                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("CrossModuleJoinId")
                        .HasColumnType("int");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("int");

                    b.HasKey("ReportId", "CrossModuleJoinId");

                    b.HasIndex("CrossModuleJoinId");

                    b.ToTable("ReportJoins");
                });

            modelBuilder.Entity("CrossModuleJoin", b =>
                {
                    b.HasOne("JoinOperand", "LeftOperand")
                        .WithMany()
                        .HasForeignKey("LeftOperandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JoinOperand", "RightOperand")
                        .WithMany()
                        .HasForeignKey("RightOperandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeftOperand");

                    b.Navigation("RightOperand");
                });

            modelBuilder.Entity("DatasetReports", b =>
                {
                    b.HasOne("DatasetsOfReports", "DatasetsOfReports")
                        .WithMany()
                        .HasForeignKey("DatasetsOfReportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Report", "Report")
                        .WithMany("DatasetsReports")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatasetsOfReports");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniMonitor.Shared.Dtos.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniMonitor.Server.Models.SharedLink", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DashboardDto", "Dashboard")
                        .WithMany()
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dashboard");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetAM", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.Datasets", "Datasets")
                        .WithMany("DatasetAM")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datasets");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetAlert", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetEM", "Dataset")
                        .WithMany("DatasetAlerts")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetAsset", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetAM", "DatasetAM")
                        .WithMany("Grupo_Asset")
                        .HasForeignKey("DatasetAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatasetAM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetCategory", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetEM", "Dataset")
                        .WithMany("DatasetCategory")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetDevice", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetIM", "Dataset")
                        .WithMany("DatasetDevices")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEM", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.Datasets", "Datasets")
                        .WithMany("DatasetEM")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datasets");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEvent", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetUM", "Dataset")
                        .WithMany("DatasetEvents")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEventEM", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetEM", "Dataset")
                        .WithMany("DatasetEvents")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEventTaskInstance", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetAM", "DatasetAM")
                        .WithMany("Grupo_Event_Task_Instance")
                        .HasForeignKey("DatasetAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatasetAM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetExtension", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetEM", "Dataset")
                        .WithMany("DatasetExtensions")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetIM", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.Datasets", "Datasets")
                        .WithMany("DatasetIM")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datasets");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetNews", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetUM", "Dataset")
                        .WithMany("DatasetNews")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetStock", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetAM", "DatasetAM")
                        .WithMany("Grupo_Stock")
                        .HasForeignKey("DatasetAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniMonitor.Shared.Dtos.DatasetEventTaskInstance", null)
                        .WithMany("Grupo_Stock")
                        .HasForeignKey("DatasetEventTaskInstanceId");

                    b.Navigation("DatasetAM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetUM", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.Datasets", "Datasets")
                        .WithMany("DatasetUM")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datasets");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.GrupoDataset", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.Datasets", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniMonitor.Shared.Dtos.Visualizacion", "Visualizacion")
                        .WithMany("GrupoDatasets")
                        .HasForeignKey("VisualizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("Visualizacion");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.GrupoVisualizacion", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.DashboardDto", "Dashboard")
                        .WithMany("GrupoVisualizaciones")
                        .HasForeignKey("GrupoVisualizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniMonitor.Shared.Dtos.Visualizacion", "Visualizacion")
                        .WithMany()
                        .HasForeignKey("IdVisualizacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OmniMonitor.Shared.Dtos.Kpi", "Kpi")
                        .WithMany()
                        .HasForeignKey("KpiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dashboard");

                    b.Navigation("Kpi");

                    b.Navigation("Visualizacion");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.RolePermission", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniMonitor.Shared.Dtos.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.UserRole", b =>
                {
                    b.HasOne("OmniMonitor.Shared.Dtos.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniMonitor.Shared.Dtos.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReportJoin", b =>
                {
                    b.HasOne("CrossModuleJoin", "CrossModuleJoin")
                        .WithMany()
                        .HasForeignKey("CrossModuleJoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Report", "Report")
                        .WithMany("ReportJoins")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrossModuleJoin");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DashboardDto", b =>
                {
                    b.Navigation("GrupoVisualizaciones");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetAM", b =>
                {
                    b.Navigation("Grupo_Asset");

                    b.Navigation("Grupo_Event_Task_Instance");

                    b.Navigation("Grupo_Stock");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEM", b =>
                {
                    b.Navigation("DatasetAlerts");

                    b.Navigation("DatasetCategory");

                    b.Navigation("DatasetEvents");

                    b.Navigation("DatasetExtensions");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetEventTaskInstance", b =>
                {
                    b.Navigation("Grupo_Stock");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetIM", b =>
                {
                    b.Navigation("DatasetDevices");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.DatasetUM", b =>
                {
                    b.Navigation("DatasetEvents");

                    b.Navigation("DatasetNews");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Datasets", b =>
                {
                    b.Navigation("DatasetAM");

                    b.Navigation("DatasetEM");

                    b.Navigation("DatasetIM");

                    b.Navigation("DatasetUM");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OmniMonitor.Shared.Dtos.Visualizacion", b =>
                {
                    b.Navigation("GrupoDatasets");
                });

            modelBuilder.Entity("Report", b =>
                {
                    b.Navigation("DatasetsReports");

                    b.Navigation("ReportJoins");
                });
#pragma warning restore 612, 618
        }
    }
}
